const DataWork = {
  mainTitle: ["즐겁게", "일해요"],
  subTitle: "프로모션",
  slide: [
    {
      id: 6,
      title: "사내 프로젝트<br />디자인 프레임워크",
      img: "/db/work/w_slide_6.png",
      type: ["적응형", "PC"],
      desc: "미디어로그 디자인팀 프로젝트",
      url: "https://leh317.iwinv.net/work/slide/6/dstudio.html",
      ia: "",
    },
    {
      id: 7,
      title: "ATOPS<span>(인공지능산업융합사업단)</span><br />관리자 페이지",
      img: "/db/work/w_slide_7.png",
      type: ["IA", "적응형", "PC"],
      desc: "화면목록, 퍼블 산출물 확인",
      url: "",
      ia: "https://leh317.iwinv.net/work/slide/7/pub",
    },
    {
      id: 4,
      title: "ATOPS<span>(인공지능산업융합사업단)</span><br />사용자지원포털",
      img: "/db/work/w_slide_4.png",
      type: ["반응형"],
      desc: "메인작업(fullpage), react-ts 기반",
      url: "https://portal.atops.or.kr/",
      ia: "",
    },
    {
      id: 5,
      title: "ATOPS<span>(인공지능산업융합사업단)</span><br />실증지원포털",
      img: "/db/work/w_slide_5.png",
      type: ["반응형"],
      desc: "메인작업(fullpage), react-ts 기반",
      url: "https://portal.atops.or.kr/tsp/",
      ia: "",
    },
    {
      id: 1,
      title: "ATOPS<span>(인공지능산업융합사업단)</span><br />데이터유통포털",
      img: "/db/work/w_slide_1.png",
      type: ["IA", "반응형"],
      desc: "화면목록, 퍼블 산출물 확인",
      url: "https://portal.atops.or.kr/dxp/main",
      ia: "https://leh317.iwinv.net/work/slide/1/pub",
    },
    {
      id: 3,
      title: "ATOPS<span>(인공지능산업융합사업단)</span><br />토탈 검색 페이지",
      img: "/db/work/w_slide_3.png",
      type: ["반응형"],
      desc: "검색작업, react-ts 기반",
      url: "https://portal.atops.or.kr/search",
      ia: "",
    },
    {
      id: 2,
      title: "ATOPS<span>(인공지능산업융합사업단)</span><br />안심구역포털",
      img: "/db/work/w_slide_2.png",
      type: ["IA", "반응형"],
      desc: "화면목록, 퍼블 산출물 확인",
      url: "https://portal.atops.or.kr/saz/svc/main/main.do",
      ia: "https://leh317.iwinv.net/work/slide/2/pub",
    },
    {
      id: 8,
      title: "한국관광공사<br /><span>(Visit Korea) </span>리뉴얼",
      img: "/db/work/w_slide_8.png",
      type: ["IA"],
      desc: "화면목록, 퍼블 산출물 확인(이은혜)",
      url: "",
      ia: "https://leh317.iwinv.net/work/slide/8/publish/pub",
    }
  ],
  banner: [
    {
      id: 1,
      title: "수고했어, 올해도",
      img: "/db/work/w_banner_1.jpg",
      url: "https://leh317.iwinv.net/work/banner/1",
    },
    {
      id: 2,
      title: "휴대폰결제 이벤트",
      img: "/db/work/w_banner_2.jpg",
      url: "https://leh317.iwinv.net/work/banner/2",
    },
    {
      id: 3,
      title: "멤버스이벤트 출석체크",
      img: "/db/work/w_banner_3.jpg",
      url: "https://leh317.iwinv.net/work/banner/3",
    },
    {
      id: 4,
      title: "휴대폰 첫결제 이벤트, 여름안에서",
      img: "/db/work/w_banner_4.jpg",
      url: "https://leh317.iwinv.net/work/banner/4",
    },
    {
      id: 5,
      title: "휴대폰 첫결제 이벤트, 힘을내요 슈퍼팔월",
      img: "/db/work/w_banner_5.jpg",
      url: "https://leh317.iwinv.net/work/banner/5",
    },
    {
      id: 6,
      title: "혹시 휴대폰 결제를 아시나요?",
      img: "/db/work/w_banner_6.jpg",
      url: "https://leh317.iwinv.net/work/banner/6",
    },
    {
      id: 7,
      title: "휴대폰 결제 이벤트, 11월엔 1원 더하세요",
      img: "/db/work/w_banner_7.jpg",
      url: "https://leh317.iwinv.net/work/banner/7",
    },
    {
      id: 8,
      title: "휴대폰 결제 이벤트, 새해에도 혜택이 소복",
      img: "/db/work/w_banner_8.jpg",
      url: "https://leh317.iwinv.net/work/banner/8",
    },
    {
      id: 9,
      title: "휴대폰 결제 이벤트, 대봄단결",
      img: "/db/work/w_banner_9.jpg",
      url: "https://leh317.iwinv.net/work/banner/9",
    },
  ],
};

export default DataWork;
